# Generated by Django 5.0.6 on 2024-10-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district', models.IntegerField()),
                ('area', models.IntegerField()),
                ('perimeter', models.IntegerField()),
                ('congress', models.IntegerField()),
                ('party', models.CharField(choices=[('R', 'Republican'), ('D', 'Democratic')], default='', max_length=1)),
            ],
        ),
    ]
