# Generated by Django 5.0.6 on 2024-10-05 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_state_district_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='state',
        ),
    ]
