# Generated by Django 5.0.6 on 2024-10-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_district_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='democratic_votes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='republican_votes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='district',
            name='area',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='district',
            name='perimeter',
            field=models.FloatField(),
        ),
    ]
